import streamlit as st
from langchain_core.prompts import PromptTemplate, load_prompt
from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline


st.set_page_config(
    page_title="AI - DYNAMIC PROMPT",
    page_icon="🤖",
    layout="centered"
)

st.title("🤖 AI - DYNAMIC PROMPT")
st.markdown("Ask me anything!")

@st.cache_resource
def load_model():
    Smollm = HuggingFacePipeline.from_model_id(
        model_id="HuggingFaceTB/SmolLM2-135M-Instruct",
        task="text-generation",
        pipeline_kwargs={
            "temperature": 0.5,
            "max_new_tokens": 100,
            "return_full_text": False
        }
    )
    return ChatHuggingFace(llm=Smollm)

with st.spinner("Loading AI Model..."):
    model = load_model()

library = st.selectbox("Select the library",["sk-learn","pandas","numpy","basic python"])
level = st.selectbox("Select level",["beginner","advanced","expert"])
size = st.selectbox("Select lines",["1","2","3","10"])

#loading template from json which is generated by prompt generator
template = load_prompt('template.json')

#fill the placeholder

prompt = template.invoke({
    'library':library,
    'level':level,
    'size':size
})


if st.button("submit"):
    with st.spinner("Thinking..."):
            result = model.invoke(prompt)

    st.success("Response Generated")
    

    st.markdown("### 🤖 AI Response")
    st.write(result.content)         
